name: samid_multiplatform
description: "This is the emigration of SAMID"
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^2.1.0
  device_preview: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/facebook_logo.png
    - assets/images/google_logo.png
    - assets/images/usuarios.png
    - assets/images/chart.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat.ttf
        - asset: assets/fonts/montserrat_bold.ttf
        - asset: assets/fonts/montserrat_regular.ttf
        - asset: assets/fonts/montserrat_semi_bold.ttf
        - asset: assets/fonts/montserrat_thin.ttf
          weight: 700
